"""Protocols for model routing domain."""
from typing import Protocol


class ModelRouter(Protocol):
    async def route(self, query: str, history: list[dict]) -> str: ...
    async def classify(self, query: str) -> str: ...
    def fallback_from(self, model_name: str) -> str | None: ...
