"""Protocols for tool sandbox domain."""
from typing import Protocol


class ToolSandbox(Protocol):
    def validate_path(self, path: str, workspace_root: str) -> bool: ...
    def validate_command(self, command: str) -> bool: ...
    def allowed_dirs(self) -> list[str]: ...
